[[Plugins]]
name = "enabled_plugins"
type = "picker"
# Options are being generated dynamically by parsing the plugin directory
options = []

[[UI]]
name = "surname"
type = "text"

[[UI]]
name = "theme"
type = "select"
options = ["default", "modern", "old"]

[[UI]]
name = "dark"
type = "checkbox"
text = "Dark theme"
