INFLUXDB_TOKEN="yHEV38yBrZxVCJc0zHEe6ZvOhR-5NXmXvvSxmGXBxlckKsc1sRmnBamLrzTT8cIbIxQXI1KUiJkQSIVrCv7ajw=="
INFLUXDB_ORG="org"
INFLUXDB_URL="http://localhost:8086"
INFLUXDB_BUCKET="MISP-Fleet-Commander"
