{
 "title": "CIRCL Monitoring MISP",
 "time": { "from": "2025-01-06T13:15:43.059Z", "to": "2025-01-17T09:48:30.254Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "MISP Instance",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"${bucket}\", tag: \"instance\")\n"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "buckets() |> filter(fn: (r) => r.name !~ /^_/) |> rename(columns: {name: \"_value\"}) |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  { "title": "Aggregated Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All MISP Versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"version\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"version\"\n  )\n  |> last()\n  |> keep(columns: [\"_value\", \"instance\", \"url\"])\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Login",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"logins\")\n  |> group(columns: [\"instance\"])\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: true)"
    }
   ]
  },
  { "title": "MISP `${instance}` Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"version\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"version\"\n  )\n  |> last()\n  |> keep(columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "# Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"event_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Objects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"object_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Attributes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"attribute_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Event Report",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"eventreport_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Analyst Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"analyst_data_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"proposal_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Correlations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"correlation_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Data count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"event_count\" or\n      r[\"_field\"] == \"attribute_count\" or\n      r[\"_field\"] == \"object_count\" or\n      r[\"_field\"] == \"correlation_count\" or\n      r[\"_field\"] == \"proposal_count\" or\n      r[\"_field\"] == \"eventreport_count\" or\n      r[\"_field\"] == \"analyst_data_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Organisations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"org_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"user_count\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Usr/Org",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"average_user_per_org\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "PGP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"user_count\" or\n      r[\"_field\"] == \"user_count_pgp\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.user_count_pgp) / float(v: r.user_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Local/Global Orgs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"org_count\" or\n      r[\"_field\"] == \"local_org_count\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.local_org_count) / float(v: r.org_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Open registration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"open_self_registration\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: max)\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Contributing Org.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"contributing_org_count\" or\n      r[\"_field\"] == \"org_count\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.contributing_org_count) / float(v: r.org_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 7d, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"logins\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"daily_time\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Login Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\" and r[\"scope\"] == \"logins\")\n  |> group()\n  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily SQL Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"sql_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sql_time\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value / 1024}))\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Redis Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"redis_info\")\n  |> filter(fn: (r) => \n    r[\"_field\"] == \"used_memory\" or\n    r[\"_field\"] == \"used_memory_peak\" or\n    r[\"_field\"] == \"db_13_keys\"\n  )\n  |> aggregateWindow(every: 6h, fn: max)\n  |> fill(usePrevious: true)\n  \n  "
    }
   ]
  },
  {
   "title": "Workers Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"workers\")\n  |> filter(fn: (r) => \n    r[\"_field\"] == \"cache_job_count\" or\n    r[\"_field\"] == \"default_job_count\" or\n    r[\"_field\"] == \"email_job_count\" or\n    r[\"_field\"] == \"prio_job_count\" or\n    r[\"_field\"] == \"update_job_count\"\n  )\n  |> aggregateWindow(every: 6h, fn: max)\n  |> fill(usePrevious: true)\n  \n  "
    }
   ]
  }
 ]
}