{
 "title": "CIRCL Monitoring MISP",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "MISP Instance",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"circl-monitoring\", tag: \"misp-name\")\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "MISP `${instance}` Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"version\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"version\"\n  )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "# Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"event_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Objects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"object_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Attributes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"attribute_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"proposal_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Correlations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"correlation_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "# Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"user_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "# Organisations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"org_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Open Self-registration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"open_self_registration\")\n  |> group()\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Data count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"event_count\" or\n      r[\"_field\"] == \"attribute_count\" or\n      r[\"_field\"] == \"object_count\" or\n      r[\"_field\"] == \"correlation_count\" or\n      r[\"_field\"] == \"proposal_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n"
    }
   ]
  },
  {
   "title": "Users/Orgs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"average_user_per_org\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Ratio of PGP User",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"user_count\" or\n      r[\"_field\"] == \"user_count_pgp\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.user_count_pgp) / float(v: r.user_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Contributing Organisation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"contributing_org_count\" or\n      r[\"_field\"] == \"org_count\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.contributing_org_count) / float(v: r.org_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Local/Global Orgs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"data_stats\")\n  |> filter(fn: (r) =>\n      r[\"_field\"] == \"org_count\" or\n      r[\"_field\"] == \"local_org_count\"\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(\n      fn: (r) => ({\n          _time: r._time,\n          _field: \"Ratio\",\n          _value: float(v: r.local_org_count) / float(v: r.org_count) * 100.0,\n      }),\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  |> group()"
    }
   ]
  },
  {
   "title": "Login",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"logins\")\n  |> group()\n  |> aggregateWindow(every: 5m, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"daily_time\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Login Heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 21, "w": 11, "x": 10, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\" and r[\"scope\"] == \"logins\")\n  |> group()\n  |> aggregateWindow(every: 5m, fn: count, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily SQL Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"sql_time\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sql_time\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Daily Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"benchmark\" and r[\"benchmark_scope\"] == \"endpoint\")\n  |> filter(fn: (r) => r[\"benchmark_field\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> group(columns: [\"endpoint\"])\n  |> max(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value / 1024}))\n  |> group()\n  |> top(n: 5)"
    }
   ]
  },
  {
   "title": "Redis Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"redis_info\")\n  |> filter(fn: (r) => \n    r[\"_field\"] == \"used_memory\" or\n    r[\"_field\"] == \"used_memory_peak\" or\n    r[\"_field\"] == \"db_13_keys\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  \n  "
    }
   ]
  },
  {
   "title": "Workers Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"circl-monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"instance\"] == \"${instance}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MISP\")\n  |> filter(fn: (r) => r[\"scope\"] == \"diagnostic\" and r[\"diagnostic_scope\"] == \"workers\")\n  |> filter(fn: (r) => \n    r[\"_field\"] == \"cache_job_count\" or\n    r[\"_field\"] == \"default_job_count\" or\n    r[\"_field\"] == \"email_job_count\" or\n    r[\"_field\"] == \"prio_job_count\" or\n    r[\"_field\"] == \"update_job_count\"\n  )\n  |> aggregateWindow(every: 5m, fn: max)\n  |> fill(usePrevious: true)\n  \n  "
    }
   ]
  }
 ]
}