"""empty message

Revision ID: 1ec3cc9d64cf
Revises: 
Create Date: 2024-02-14 15:02:44.971950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec3cc9d64cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_user_id'), ['user_id'], unique=False)

    op.create_table('pin_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_lists_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_pin_lists_user_id'), ['user_id'], unique=False)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('skip_ssl', sa.Boolean(), nullable=False),
    sa.Column('authkey', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_uuid'), ['uuid'], unique=True)

    op.create_table('pin_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinlist_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pinlist_id'], ['pin_lists.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin_list_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_list_entries_pinlist_id'), ['pinlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pin_list_entries_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin_list_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_list_entries_server_id'))
        batch_op.drop_index(batch_op.f('ix_pin_list_entries_pinlist_id'))

    op.drop_table('pin_list_entries')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_uuid'))
        batch_op.drop_index(batch_op.f('ix_servers_user_id'))
        batch_op.drop_index(batch_op.f('ix_servers_url'))
        batch_op.drop_index(batch_op.f('ix_servers_name'))
        batch_op.drop_index(batch_op.f('ix_servers_fleet_id'))

    op.drop_table('servers')
    with op.batch_alter_table('pin_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_pin_lists_model'))

    op.drop_table('pin_lists')
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleets_user_id'))
        batch_op.drop_index(batch_op.f('ix_fleets_timestamp'))
        batch_op.drop_index(batch_op.f('ix_fleets_name'))

    op.drop_table('fleets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
