"""Added is_monitored column to fleet

Revision ID: 94674764dc33
Revises: e9dd16ee4418
Create Date: 2025-01-14 10:07:44.157043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94674764dc33'
down_revision = 'e9dd16ee4418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_monitored', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_column('is_monitored')

    # ### end Alembic commands ###
