"""Added is_watched to fleet table

Revision ID: 97a9b79324b5
Revises: 94674764dc33
Create Date: 2025-01-28 14:44:13.575248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a9b79324b5'
down_revision = '94674764dc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_watched', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_column('is_watched')

    # ### end Alembic commands ###
