"""Add apikey column to users

Revision ID: a0b8ff3cdda9
Revises: 1ec3cc9d64cf
Create Date: 2024-02-14 15:06:11.326689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b8ff3cdda9'
down_revision = '1ec3cc9d64cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('apikey')

    # ### end Alembic commands ###
